name: uammd-structured
channels:
  - conda-forge
dependencies:
  - cmake >=3.27
  - cuda-version
  - gxx 11.*
  - gcc
  - cuda-libraries-dev
  - cuda-nvcc
  - make
  - libblas
  - liblapacke
  - blas-devel
  - pybind11
  - python 3.*
  - pip
  - numpy
  - tqdm
