name: uammd-structured
channels:
  - conda-forge
dependencies:
  - cmake >=3.27
  - cuda-version < 12.8
  - gxx 11.*
  - gcc
  - cuda-libraries-dev
  - cuda-nvcc
  - make
  - mkl-devel
  - pybind11
  - python 3.*
  - pip
  - numpy
  - tqdm
  - pytest
