set -x
SRC_DIR=$(pwd)
TMPDIR=$(mktemp -d)
cd $TMPDIR
cmake -DCMAKE_PREFIX_PATH=$PREFIX -DPython_EXECUTABLE=${PYTHON} -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DINSTALL_PYTHON_PACKAGE=ON -DBUILD_PYTHON_WRAPPER=ON -DBUILD_LIBRARY=OFF $SRC_DIR
make -j4
make install
rm -rf $TMPDIR
