{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject['project']['version'] %}


package:
  name: pyuammd-structured
  version: {{ version }}

source:
  git_url: ../../../

build:
  number: 0
  string: py{{ PY_VER }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python
    - cmake
    - pybind11
    - gxx
    - pip
    - setuptools
  host:
    - python
    - uammd-structured {{ GIT_DESCRIBE_TAG }}
  run:
    - python
    - uammd-structured
    - tqdm
    - deepdiff
    - jsbeautifier

test:
  imports:
    - pyUAMMD

about:
  home: https://github.com/PabloIbannez/uammd-structured
  license: GPL3
  summary: Python wrapper for UAMMD-structured
