set -x
SRC_DIR=$(pwd)
TMPDIR=$(mktemp -d)
cd $TMPDIR
cmake $SRC_DIR -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DINSTALL_PYTHON_PACKAGE=ON -DBUILD_PYTHON_WRAPPER=ON -DCMAKE_CUDA_ARCHITECTURES=OFF  -DPython_EXECUTABLE=${PYTHON} -DUAMMD_PRECISION=${UAMMD_PRECISION}
make install -j15
rm -rf $TMPDIR
