set -x
SRC_DIR=$(pwd)
TMPDIR=$(mktemp -d)
cd $TMPDIR
cmake $SRC_DIR -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DINSTALL_PYTHON_PACKAGE=OFF -DBUILD_PYTHON_WRAPPER=OFF -DCMAKE_CUDA_ARCHITECTURES=all-major -DUAMMD_PRECISION=$UAMMD_PRECISION -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=256 -DBUILD_LIBRARY=ON
make -j4
make install
rm -rf $TMPDIR
