name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Sunday at midnight
    - cron:  '0 0 * * 0'

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: ${{ matrix.name }}
#    runs-on: ubuntu-latest
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest supported versions
          - name: Linux (CUDA 12)
            cuda: "12.*"
            gcc: "13.*"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Prepare dependencies
      run: |
        sed -i -e "/cuda-version/c\  - cuda-version ${{ matrix.cuda }}" \
               -e "/gxx/c\  - gxx ${{ matrix.gcc }}" \
               environment.yml
    - name: Show dependency file
      run: cat environment.yml
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        auto-activate-base: false
        miniforge-version: latest
        activate-environment: build
        channel-priority: strict
        channels: conda-forge
        conda-remove-defaults: true      
    - name: Configure and compile
      run: |
        micromamba activate uammd
        mkdir build && cd build
        cmake -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_CUDA_ARCHITECTURES=OFF -DBUILD_PYTHON_WRAPPER=ON -DINSTALL_PYTHON_PACKAGE=ON -DBUILD_LIBRARY=ON -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=64 ..
        make -j4 install

