name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Sunday at midnight
    - cron:  '0 0 * * 0'

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: ${{ matrix.name }}
#    runs-on: ubuntu-latest
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest supported versions
          - name: Linux (CUDA 12)
            cuda: "12.*"
            gcc: "13.*"
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Prepare dependencies
      run: |
        sed -i -e "/cuda-version/c\  - cuda-version ${{ matrix.cuda }}" \
               -e "/gxx/c\  - gxx ${{ matrix.gcc }}" \
               environment.yml
    - name: Show dependency file
      run: cat environment.yml
      
    - name: Install Mamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        cache-environment: false
        cache-downloads: true
        generate-run-shell: true
      env:
        CONDA_OVERRIDE_CUDA: ${{ matrix.nvcc }}

    - name: List environment
      run: |
        micromamba activate uammd
        micromamba list
      shell: micromamba-shell {0}
      
    - name: Configure and compile
      run: |
        micromamba activate uammd
        mkdir build && cd build
        cmake -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_CUDA_ARCHITECTURES=OFF -DBUILD_PYTHON_WRAPPER=ON -DINSTALL_PYTHON_PACKAGE=ON -DBUILD_LIBRARY=ON -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=64 ..
        make -j4 install

      shell: micromamba-shell {0}
