name: Build and upload conda packages
on:
  release:
    types: ['released', 'prereleased']
# lets add on PR for testing
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
#    runs-on: [self-hosted, gpu]
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12", "3.13"]
        cuda-version: ["12.1", "12.3", "12.6", "12.9"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
          cache-environment: true
          cache-downloads: true
          generate-run-shell: true

      - name: Build and upload the conda packages manually
        shell: micromamba-shell {0}
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          UAMMD_STRUCTURED_PACKAGE_NAME: uammd-structured
          UAMMD_PRECISION: "SINGLE"
        run: |
          out_dir=`mktemp -d -t compilation-XXXXXXXXXX`
          conda verify devtools/conda-build
          conda build devtools/conda-build --python "$PYTHON_VERSION" --no-anaconda-upload --output-folder $out_dir
          pkg_files=`find ${out_dir} -name *.conda`
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload ${pkg_files} \
            --user ComplexFluidsUAM \
            --label main \
            --force
