name: Build and upload conda packages
on:
  release:
    types: ['released', 'prereleased']
# lets add on PR for testing
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
#    runs-on: ubuntu-latest
    runs-on: [self-hosted, gpu]
    strategy:
      matrix:
        cuda-version: ["12.1", "12.3", "12.6", "12.9"]
        include:
          - cuda-version: "12.1"
            build-py-wrapper: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
          cache-environment: true
          cache-downloads: true
          generate-run-shell: true

      - name: Build and upload uammd-structured
        shell: micromamba-shell {0}
        env:
          CUDA_VERSION: ${{ matrix.cuda-version }}
        run: |
          out_dir=`mktemp -d -t uammd-structured-XXXXXXXXXX`
          conda verify devtools/conda-build/uammd-structured
          conda build devtools/conda-build/uammd-structured --no-anaconda-upload --output-folder ${out_dir} -c conda-forge
          find ${out_dir} -name '*.conda' -print0 | xargs -0 anaconda --verbose -t ${{ secrets.ANACONDA_TOKEN }} upload  --user ComplexFluidsUAM --label main --force
          
      - name: Build and upload pyuammd-structured
        if: ${{ matrix.build-py-wrapper == true }}
        shell: micromamba-shell {0}
        run: |
          out_dir=$(mktemp -d -t pyuammd-XXXXXXXXXX)
          conda verify devtools/conda-build/pyuammd-structured
          conda build devtools/conda-build/pyuammd-structured --no-anaconda-upload --output-folder ${out_dir} -c conda-forge --use-local
          find ${out_dir} -name '*.conda' -print0 | xargs -0 anaconda --verbose -t ${{ secrets.ANACONDA_TOKEN }} upload  --user ComplexFluidsUAM --label main --force

